agents:
  provider: "gcp"
  machineType: "n1-standard-2"
  image: family/enterprise-search-ubuntu-2204-connectors-py

steps:
  - label: ":wrench: Linting"
    command: 'docker run -v `pwd`:/ci -w=/ci --rm --name jenkins-linter -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3 make lint'
  - label: ":safety_vest: Testing"
    command: 'docker run -v `pwd`:/ci -w=/ci --rm --name jenkins-linter -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3 make test'
  - label: ":safety_vest: Test Coverage"
    command: 'docker run -v `pwd`:/ci -w=/ci --rm --name jenkins-linter -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3 make cover'
